import {
  MessageSquarePlus,
  MousePointerSquare,
  Workflow,
  ShieldQuestion,
} from "lucide-react";

import type { Tool } from "~/types/tool";

export const TOOLS: Tool[] = [
  {
    label: "Automations",
    icon: Workflow,
    color: "text-red-500",
    bgColor: "bg-red-500/10",
    href: "/dashboard/",
  },
  {
    label: "Message Builder",
    icon: MessageSquarePlus,
    color: "text-violet-500",
    bgColor: "bg-violet-500/10",
    href: "/dashboard/",
  },
  {
    label: "Role Menus",
    icon: MousePointerSquare,
    color: "text-orange-500",
    bgColor: "bg-orange-500/10",
    href: "/dashboard/",
  },
  {
    label: "Logging",
    icon: ShieldQuestion,
    color: "text-red-500",
    bgColor: "bg-red-500/10",
    href: "/dashboard/",
  },
  {
    label: "Giveaways",
    icon: ShieldQuestion,
    color: "text-red-500",
    bgColor: "bg-red-500/10",
    href: "/dashboard/",
  },
  {
    label: "Moderation",
    icon: ShieldQuestion,
    color: "text-red-500",
    bgColor: "bg-red-500/10",
    href: "/dashboard/",
  },
  {
    label: "Voice Generation",
    icon: ShieldQuestion,
    color: "text-red-500",
    bgColor: "bg-red-500/10",
    href: "/dashboard/",
  },
  {
    label: "Welcomer",
    icon: ShieldQuestion,
    color: "text-red-500",
    bgColor: "bg-red-500/10",
    href: "/dashboard/",
  },
  {
    label: "Levelling",
    icon: ShieldQuestion,
    color: "text-red-500",
    bgColor: "bg-red-500/10",
    href: "/dashboard/",
  },
  {
    label: "Reminders",
    icon: ShieldQuestion,
    color: "text-red-500",
    bgColor: "bg-red-500/10",
    href: "/dashboard/",
  },
  {
    label: "Fun Commands",
    icon: ShieldQuestion,
    color: "text-red-500",
    bgColor: "bg-red-500/10",
    href: "/dashboard/",
  },
  {
    label: "Economy",
    icon: ShieldQuestion,
    color: "text-red-500",
    bgColor: "bg-red-500/10",
    href: "/dashboard/",
  },
  {
    label: "Todo List",
    icon: ShieldQuestion,
    color: "text-red-500",
    bgColor: "bg-red-500/10",
    href: "/dashboard/",
  },
  {
    label: "Custom Commands",
    icon: ShieldQuestion,
    color: "text-red-500",
    bgColor: "bg-red-500/10",
    href: "/dashboard/",
  },
  {
    label: "Message Scheduler",
    icon: ShieldQuestion,
    color: "text-red-500",
    bgColor: "bg-red-500/10",
    href: "/dashboard/",
  },
  {
    label: "Suggestions",
    icon: ShieldQuestion,
    color: "text-red-500",
    bgColor: "bg-red-500/10",
    href: "/dashboard/",
  },
  {
    label: "Counting",
    icon: ShieldQuestion,
    color: "text-red-500",
    bgColor: "bg-red-500/10",
    href: "/dashboard/",
  },
  {
    label: "Starboard",
    icon: ShieldQuestion,
    color: "text-red-500",
    bgColor: "bg-red-500/10",
    href: "/dashboard/",
  },
  {
    label: "Verification",
    icon: ShieldQuestion,
    color: "text-red-500",
    bgColor: "bg-red-500/10",
    href: "/dashboard/",
  },
  {
    label: "Forms",
    icon: ShieldQuestion,
    color: "text-red-500",
    bgColor: "bg-red-500/10",
    href: "/dashboard/",
  },
  {
    label: "Discussions",
    icon: ShieldQuestion,
    color: "text-red-500",
    bgColor: "bg-red-500/10",
    href: "/dashboard/",
  },
  {
    label: "Highlighter",
    icon: ShieldQuestion,
    color: "text-red-500",
    bgColor: "bg-red-500/10",
    href: "/dashboard/",
  },
];
